### ISSUE TITLE
catching unlock AND unlatch to trigger a scene

### ISSUE THREAD

**Issue by aebgit** [benzman81/homebridge-nukiio#16]
Hi Benzman81,

thanks a lot for your homebridge-plugin!
I have a lock with latch, and try to trigger a homekit-scene, when i unlock AND unlatch my door. Do you have a suggestion how i could achieve this? It seems to me, that the "lockname Unlatch" and "lockname" devices are triggered simultaneously, independent if i unlatch the lock or if i unlock AND unlatch it.
I want to use homekit-integration here only for the triggering of scene(s). For unlocking/unlatching i use Nukis AutoUnlock.

Thanks in advance!

Andreas

**Comment by benzman81** [comment]
I asked in the slack channel just to be sure if I remember correctly. This is the official answer: "Callbacks are called after every state change and they contain the current state (which is never "unlatched" because when the bridge connects it's already back to unlocked)" So there is no way to trigger anything for "unlatch".
