### ISSUE TITLE
Errors with iOS 10

### ISSUE THREAD

**Issue by marcoraddatz** [benzman81/homebridge-nukiio#2]
Hey benzman,

thanks for creating this package. I just want to ask, whether it works for you correctly? If I try to use it with iOS 10, I always receive the same error messages:

```
[9/24/2016, 6:51:31 PM] [Front Door] Error occured requesting lock state. This might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'.
[9/24/2016, 6:51:39 PM] [Front Door] Process lock action '2' for Nuki lock '0' of Nuki bridge '0'.
[9/24/2016, 6:51:39 PM] [Front Door] An error occured processing lock action.
```

Credentials are correct. Verified them by creating requests to my bridge and getting correct JSON. Before I dive into debugging, I wanted to make sure, it's been tested... :)

/Edit: Might there be a relation to #1 ?

**Comment by benzman81** [comment]
Hi,

this is not related to #1 .

The plugin is currently under heavy development, since the plugin development started based on a dummy server faking a nuki Bridge. Now, since I  received the hardware bridge, there has been a lot of issues that I am currently still working on. But in the end I always try to provide a "mostly" working version. Currently there is still an issue, where my hardware bridge is doing a restart when I open the Home-App once in a while and Doors with door latches do not work well. Both is in work.

The first "error" you see is a message that appears, because HomeKit or Homebridge always sends two request to get the state. The Bridge can not handle multiple request well. Because of this, I added a request Queue. For example, if a state request is requested a one is still running, the second one does not get executed and Returns a cached value. This Queue is in early stage, but I have not found any issues on that. Maybe I should not print this as an error, as this is wanted behavior. I am already heavily in contact with Nuki to dig into all These issues to provide a stable plugin.

For my self, I found out, that I currently wouldnt automate any Actions at this early stage and that the best experience is using siri since I had not any issues with this.

Do you use a Hardware or Software Bridge? Do you have single lock or multiple.

By the way, help is very welcome. Feel free to create pull requests.

Regards,
Markus

**Comment by benzman81** [comment]
Added part of this text to the readme.

**Comment by marcoraddatz** [comment]
Hey Markus,

many thanks for your quick response.

I use a DiskStation 415+ with Homebridge in a Docker container. The hacky source is published under https://github.com/marcoraddatz/homebridge-docker. I currently play around with the timeouts and will let you know, once I figure out, why Nuki isn't responding at all.

**Comment by benzman81** [comment]
Just as side node, I'am running home bridge on Diskstation with Docker, too.
Using this image https://github.com/cbrandlehner/homebridge-docker, but shouldnt make any differences.

**Comment by marcoraddatz** [comment]
I found the reason why it didn't work. I couldn't use the default port 8080, because it's already in use in my local network and caused a conflict. By using port 9080 with `"bridge_url": "http://192.168.1.73:9080"` all works fine. Many thanks for your efforts and the updated error logs! :)
