### ISSUE TITLE
Only unlatch if current state is unlocked

### ISSUE THREAD

**Issue by tschortsch3711** [benzman81/homebridge-nukiio#41]
Currently, if the door is locked and I hit the 'always unlatch' button, it unlocks AND unlatches the door. Is it possible to add an options to only unlatch the door if the current state is unlocked?

I am using the auto unlock feature of the Nuki App, however, sometimes I don't reach the door fast enough to open it while the latch is pulled (and I don't want to extend the time).
Therefore it would be great to have a button in control center to just unlatch the door if it is already unlocked (and not unlock the door and then unlatch).

I want to avoid unlocking my door if I accidentally hit any unlock button from control center.

I hope it is clear what I'm trying to say, otherwise let me know. Cheers

**Comment by benzman81** [comment]
Hitting a lock button which state is already open will trigger a close of the door since home kit does not know door latches. This is why I added the three locks if you have a door with a door latch. For my case, I always pull the latch using Siri.  Telling it "Hey Siri, Open the FooDoor" it will always execute the open door action regardless of its current state.

**Comment by benzman81** [comment]
@tschortsch3711 With v0.10.0 you can now use automations/scenes to dis-/allow unlatching.
