### ISSUE TITLE
Enhancement: support for the upcoming Nuki Opener

### ISSUE THREAD

**Issue by CooperCGN** [benzman81/homebridge-nukiio#42]
Any plans to support it?

https://nuki.io/de/blog/nuki-news-de/nuki-opener-die-ersten-einladungen-sind-verschickt/

**Comment by benzman81** [comment]
Since I don‘t have or will buy a nuki opener, I will not be able to test it. But I would accept pull requests to support those new features.

**Comment by apfelflo89** [comment]
I would guess you don´t really need help with updating the api calls, there is just a new parameter that was added with the opener, called device type. with 0 for smartlock and 2 for opener. Just look at the new API docu:

https://developer.nuki.io/page/nuki-bridge-http-api-190/4/#heading--introduction

If you need help with testing the plugin a could do that since I already  own a Opener

**Comment by benzman81** [comment]
@CooperCGN @apfelflo89 there is now a branch openersupport you can test. This is developed completely blind, so I fully depend on yours tests to collect bugs and verify functionality. If it works, it will get merged into master and published via npm. You can open, set RingToOpen and set Continuous Mode. Hopefully there are not may bugs.

You can install it as example via: 
`npm install -g 'benzman81/homebridge-nukiio#openersupport' --unsafe-perm`

**Comment by benzman81** [comment]
@CooperCGN @apfelflo89 support of opener is merged into master and is be published to npm. There is still some "bug" with iOS 13 in Homebridge or at Apple. See #49.
